In [3]:
from utils.preprocessing import load_data

from src.collaborative_filtering import (
    get_cf_recommendations
)

from src.content_based import (
    get_cb_recommendations,
    get_similar_movies
)

from src.recommender import (
    get_hybrid_recommendations
)

In [4]:
(
    movies_data,
    ratings_data,
    movie_ratings_data,
    tfidf_matrix
) = load_data()

In [6]:
ratings_data.head()

   userId  movieId  rating            timestamp
0       1        2     3.5  2005-04-02 23:53:47
1       1       29     3.5  2005-04-02 23:31:16
2       1       32     3.5  2005-04-02 23:33:39
3       1       47     3.5  2005-04-02 23:32:07
4       1       50     3.5  2005-04-02 23:29:40

In [7]:
print("Películas:", len(movies_data))
print("Ratings:", len(ratings_data))
print("Usuarios:", ratings_data["userId"].nunique())

Películas: 27278
Ratings: 20000263
Usuarios: 138493

In [8]:
user_id = 1

In [9]:
cf_recommendations = get_cf_recommendations(
    user_id=user_id,
    n=5,
    movie_ratings_data=movie_ratings_data,
    movies_data=movies_data
)

cf_recommendations

,title,genres
9323,"O Auto da Compadecida (Dog's Will, A) (2000)",Adventure|Comedy
9797,"Phone Box, The (Cabina, La) (1972)",Comedy|Drama|Mystery|Thriller
11683,God Grew Tired of Us (2006),Documentary|Drama
17444,Between the Folds (2008),Documentary
18683,"Very Potter Musical, A (2009)",Comedy|Musical

In [10]:
similar_movies = get_similar_movies(
    movie_id=1,
    n=5,
    movies_data=movies_data,
    tfidf_matrix=tfidf_matrix
)

In [11]:
hybrid_recommendations = get_hybrid_recommendations(
    user_id=user_id,
    n=5,
    movie_ratings_data=movie_ratings_data,
    movies_data=movies_data,
    tfidf_matrix=tfidf_matrix
)

In [12]:
print("=" * 50)
print("RECOMENDACIONES HÍBRIDAS")
print("=" * 50)

for i, row in enumerate(
    hybrid_recommendations.itertuples(),
    start=1
):
    print(f"{i}. {row.title}")
    print(f"   Géneros: {row.genres}")
    print()

==================================================
RECOMENDACIONES HÍBRIDAS
==================================================
1. 47 Ronin (2013)
   Géneros: Action|Adventure|Fantasy

2. 7th Voyage of Sinbad, The (1958)
   Géneros: Action|Adventure|Fantasy

3. About Time (2013)
   Géneros: Drama|Fantasy|Romance

4. Barbarian Queen II: The Empress Strikes Back (1990)
   Géneros: Action|Adventure|Fantasy

5. Casey Jones (2011)
   Géneros: Action|Adventure|Fantasy